from collections import defaultdict
from rouge_score import rouge_scorer
from codebleu import calc_codebleu
import evaluate
import sacrebleu
import re
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.translate.meteor_score import single_meteor_score
import logging
from .eval_source_code import create_docker_container, \
                             compile_and_run_c_code_in_docker, \
                             compile_and_run_cpp_code_in_docker, \
                             compile_and_run_python_code_in_docker
from .eval_asm_code import run_x86_assmbly_code, \
                            run_x64_assmbly_code, \
                            run_arm32_assmbly_code, \
                            run_mips32_assmbly_code
from .new_eval_asm_code import compile_and_run_x64_assembly_code_in_docker, \
                                compile_and_run_x86_assembly_code_in_docker
from .config import TASKTYPE_EVALUATOR_DICT
from .data import read_jsonl, read_problems

class Evaluator:
    def evaluate(self, problem: dict) -> dict:
        '''
        @para problem: dict, contain all information needed to evaluate a solution of the problem
            field: 
                task_id: int, unique id of the problem
                task_type: str, type of the problem
                input: str, input of the problem
                output: str, output of the problem, i.e., label
                default_instruction: str, default instruction of the problem
                completion: str, completion of the problem, generated by model
                language[optional]: str, language of the problem, [C,C++,Python,JavaScript,ASM_x86,ASM_x64,ASM_ARM,ASM_MIPS]
                test_cases[optional]: list[list[str, str]], inputs of the program, in each item, item[0] is input, item[1] is expected output
        @return: dict, evaluation metrics, e.g., {"metric_a": 0.5, "metric_b": 0.6}
        '''
        raise NotImplementedError

class KeywordsEvaluator(Evaluator):
    def _search_whole_word(word, text):
        import re
        pattern = r'\b{}\b'.format(word)
        return re.search(pattern, text, re.IGNORECASE) is not None
    def _identify_keywords(text) -> list:
        # use a LLM to identify keywords
        raise NotImplementedError
    def evaluate(self, problem) -> dict:
        raise NotImplementedError
    
class SafeCodeEvaluator(Evaluator):
    """use docker"""
    def __init__(self) -> None:
        super().__init__()
        self.container_name = create_docker_container()

    def evaluate(self, problem) -> dict:
        code = problem.get('completion')
        language = problem.get('language')
        test_cases = problem.get('test_cases')
        program_inputs = [t[0] for t in test_cases]
        expected_outputs = [t[1] for t in test_cases]

        if language=='C':
            results = compile_and_run_c_code_in_docker(self.container_name, code, program_inputs, expected_outputs)
        elif language=='C++':
            results = compile_and_run_cpp_code_in_docker(self.container_name, code, program_inputs, expected_outputs)
        elif language=='Python':
            results = compile_and_run_python_code_in_docker(self.container_name, code, program_inputs, expected_outputs)
        else:
            raise NotImplementedError
        return {"pass": results}

def parse_bleu_score(bleu_output):
    pattern = r"BLEU = ([\d.]+) ([\d.]+)/([\d.]+)/([\d.]+)/([\d.]+) \(BP = ([\d.]+) ratio = ([\d.]+) hyp_len = (\d+) ref_len = (\d+)\)"
    match = re.match(pattern, bleu_output)
    if match:
        bleu_score = {
            'BLEU': float(match.group(1)),
            'BLEU_1': float(match.group(2)),
            'BLEU_2': float(match.group(3)),
            'BLEU_3': float(match.group(4)),
            'BLEU_4': float(match.group(5)),
        }
        return bleu_score
    else:
        return None

class SemanticComprehensionEvaluator(Evaluator):
    def __init__(self) -> None:
        super().__init__()
        #self.scorer = rouge_scorer.RougeScorer(['rouge1','rouge2','rougeL'], use_stemmer=True)
        self.smooth_bleu_metric = []
        self.meteor_metric = evaluate.load('meteor')
        self.rouge_metric = evaluate.load('rouge')

    def evaluate(self, problem) -> dict:
        input_code = problem.get("input")
        prediction = problem.get('completion')
        reference = problem.get('output')
        bleu = sacrebleu.corpus_bleu([prediction], [[reference]], smooth_method='exp')
        meteor_score = self.meteor_metric.compute(predictions=[prediction], references=[reference])
        rouge_score = self.rouge_metric.compute(predictions=[prediction], references=[reference])

        parsed_bleu = parse_bleu_score(str(bleu))
        return {**parsed_bleu, **meteor_score, **rouge_score, "overhead": problem.get('overhead')}


class LogicalAnalysisEvaluator(Evaluator):
    def evaluate(self, problem) -> dict:
        input_code = problem.get("input")
        prediction = problem.get('completion').strip().lower()
        reference = problem.get('output').strip().lower()
        overhead = problem.get('overhead')
        return {"accuracy": 1 if prediction==reference else 0, "overhead": overhead}

class AssemblySynthesisEvaluator(Evaluator):
    """use docker"""
    def __init__(self) -> None:
        super().__init__()
        self.container_name = create_docker_container()
        self.smooth_bleu_metric = []
        self.meteor_metric = evaluate.load('meteor')
        self.rouge_metric = evaluate.load('rouge')

    def evaluate(self, problem) -> dict:
        reference = problem.get('output')
        code = problem.get('completion')
        language = problem.get('language')
        test_cases = problem.get('test_cases')
        program_inputs = [t[0] for t in test_cases]
        expected_outputs = [t[1] for t in test_cases]
        # results = simulate_asm_code(code, language, program_inputs, expected_outputs)
        if language == "ASM_X86":
            #results = run_x86_assmbly_code(code,program_inputs,expected_outputs)
            results = compile_and_run_x86_assembly_code_in_docker(self.container_name,code,program_inputs,expected_outputs)
        elif language == "ASM_X64":
            results = compile_and_run_x64_assembly_code_in_docker(self.container_name,code,program_inputs,expected_outputs)
        elif language == "ASM_ARM32":
            results = run_arm32_assmbly_code(code,program_inputs,expected_outputs)
        elif language == "ASM_MIPS32":
            results = run_mips32_assmbly_code(code,program_inputs,expected_outputs)
        
        bleu = sacrebleu.corpus_bleu([code], [[reference]], smooth_method='exp')
        meteor_score = self.meteor_metric.compute(predictions=[code], references=[reference])
        rouge_score = self.rouge_metric.compute(predictions=[code], references=[reference])
        parsed_bleu = parse_bleu_score(str(bleu))

        return {**results, **parsed_bleu, **meteor_score, **rouge_score, "overhead": problem.get('overhead')}

class BinaryLiftingEvaluator(Evaluator):
    # """use docker"""
    # def __init__(self) -> None:
    #     super().__init__()
    #     self.container_name = create_docker_container()

    def evaluate(self, problem) -> dict:
        input_code = problem.get("input")
        decompiled_code = problem.get("completion")
        language = problem.get("language")
        source_code = problem.get("output")
        language = {
            "C":"c", 
            "C++":"cpp", 
            "Python":"python",
            "JavaScript":"javascript",}[language] # algin with codebleu
        result = calc_codebleu([source_code], [decompiled_code], 
                               lang=language, 
                               weights=(0.25, 0.25, 0.25, 0.25), 
                               tokenizer=None)
        return {**result, "overhead": problem.get('overhead')}


DefaultEvaluator = SemanticComprehensionEvaluator

def evaluate_correctness(prediction_file: str, 
                        problem_file: str, 
                        timeout: float = 5.0 ):
    # add prediction into problems
    problems = read_problems(problem_file)
    for sample in read_jsonl(prediction_file):
        task_id = sample['task_id']
        problems[task_id]['completion'] = sample['completion']
        if "gpt" in prediction_file:
            problems[task_id]['overhead'] = 0
        else:
            problems[task_id]['overhead'] = sample['overhead']
    # collect into batch
    task_groups = defaultdict(list)
    for task_id, problem in problems.items():
        task_groups[problem['task_type']].append(problem)
    # evaluate task-by-task
    task_results = defaultdict(dict)
    for task_type, task_group in task_groups.items():
        print(task_type, len(task_group))
        if task_type not in TASKTYPE_EVALUATOR_DICT:
            logging.warn(f'[!] No evaluator for task {task_type}, use default evaluator.')
            evaluator = DefaultEvaluator()
        else:
            evaluator = eval(TASKTYPE_EVALUATOR_DICT[task_type])()
        metrics = defaultdict(float)
        for problem in task_group:
            res = evaluator.evaluate(problem)
            problem['results'] = res
            metrics = {metric:metrics[metric]+res[metric] for metric in res}
        metrics = {metric:metrics[metric]/len(task_group) for metric in metrics}
        task_results[task_type] = metrics
    return task_results
    